# Generated by Django 2.2.8 on 2019-12-09 19:41

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookPayload',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('sender', models.CharField(db_index=True, max_length=64)),
                ('received_on', models.DateTimeField(auto_now_add=True,
                                                     db_index=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookpayload',
            index=django.contrib.postgres.indexes.GinIndex(
                fastupdate=False,
                fields=['payload'],
                name='tcms_github_app_payload_gin'),
        ),
    ]
