name: testing

on:
  push:
    branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build me
        run: |
          pip install -U pip "setuptools<82" wheel twine

          make package

  postgres:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        kiwitcms-url: [tcms.kiwitcms.org, public.tenant.kiwitcms.org]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create database
        run: |
          docker compose pull db
          docker compose run -d -p 5432:5432 --name postgresql_database db

      - name: Configure ~/.tcms.conf for ${{ matrix.kiwitcms-url }}
        run: |
          echo "[tcms]" > ~/.tcms.conf
          echo "url = https://${{ matrix.kiwitcms-url }}/xml-rpc/" >> ~/.tcms.conf
          echo "username = kiwitcms-bot" >> ~/.tcms.conf
          echo "password = ${{ secrets.TCMS_PASSWORD }}" >> ~/.tcms.conf

      - name: Install dependencies
        env:
          PKG_TOKEN: ${{ secrets.GEMFURY_PULL_TOKEN }}
        run: |
          sudo apt-get install libkrb5-dev

          pip install -r devel.txt \
            --index-url https://$PKG_TOKEN@pkg.kiwitcms.eu/pypi/ \
            --extra-index-url https://pypi.org/simple/

          pip install $(curl --silent https://raw.githubusercontent.com/kiwitcms/Kiwi/master/requirements/base.txt | grep PyGithub)

      - name: Execute tests
        env:
          KIWI_GITHUB_APP_ID: ${{ secrets.KIWI_GITHUB_APP_ID }}
          KIWI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.KIWI_GITHUB_APP_PRIVATE_KEY }}
          PKG_TOKEN: ${{ secrets.GEMFURY_PULL_TOKEN }}
        run: |
          # report to Kiwi TCMS only if we have access to secrets
          if [ -n "${{ secrets.TCMS_PASSWORD }}" ]; then
              export DJANGO_TEST_RUNNER="tcms_django_plugin.TestRunner"
              export TCMS_PRODUCT=$GITHUB_REPOSITORY
              export TCMS_PRODUCT_VERSION=$(echo $GITHUB_REF | sed "s|refs/heads/||" | sed "s|refs/||" | sed "s|/merge||")
              export TCMS_BUILD=$(echo $GITHUB_SHA | cut -c1-7)
          fi

          make check

      - name: Local coverage report
        run: |
          coverage report -m

      - name: Send coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
